# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
    - cmake
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
